apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machinelearningmodels.blue.intranet
spec:
  group: blue.intranet
  names:
    plural: machinelearningmodels
    singular: machinelearningmodel
    kind: MachineLearningModel
    shortNames:
    - mlm
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                artifact:
                  type: string
                command:
                  type: array
                  items:
                    type: string
              required: ["image"]
          required: ["spec"]
