apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machinelearningendpointconfigs.blue.intranet
spec:
  group: blue.intranet
  names:
    plural: machinelearningendpointconfigs
    singular: machinelearningendpointconfig
    kind: MachineLearningEndpointConfig
    shortNames:
    - mlec
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                models:
                  type: array
                  items:
                    type: object
                    properties:
                      model:
                        type: string
                      weight:
                        type: number
                      cpus:
                        type: string
                      memory:
                        type: string
                      instances:
                        type: integer
                      size:
                        type: string
                      path:
                        type: string
                    required: [ "model" ]
              required: [ "models" ]
          required: [ "spec" ]
