apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: machinelearningendpoints.blue.intranet
spec:
  group: blue.intranet
  names:
    plural: machinelearningendpoints
    singular: machinelearningendpoint
    kind: MachineLearningEndpoint
    shortNames:
    - mle
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                config:
                  type: string
                host:
                  type: string
              required: [ "config", "host" ]
            status:
              type: object
              properties:
                endpoint_config_version:
                  type: string
                state:
                  type: string
          required: [ "spec" ]
