apiVersion: v1
kind: ServiceAccount
metadata:
  name: machine-learning-operator
  namespace: ml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machine-learning-operator
rules:
- apiGroups: [ "blue.intranet" ]
  resources:
  - machinelearningmodels
  - machinelearningendpointconfigs
  - machinelearningendpoints
  verbs: [ "*" ]
- apiGroups: [ "" ]
  resources:
  - pods
  - namespaces
  - services
  - endpoints
  - persistentvolumes
  - persistentvolumeclaims
  - events
  verbs: [ "*" ]
- apiGroups: [ "apps" ]
  resources:
  - deployments
  verbs: [ "*" ]
- apiGroups: [ "" ]
  resources:
  - secrets
  verbs: [ "get" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-learning-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: machine-learning-operator
subjects:
- kind: ServiceAccount
  name: machine-learning-operator
  namespace: ml
