apiVersion: v1
kind: PersistentVolume
metadata:
  name: machine-learning-pv-volume
  labels:
    type: local
    namespace: ml
    component: machine-learning-operator
spec:
    storageClassName: manual
    capacity:
      storage: 1Gi
    accessModes:
    - ReadWriteOnce
    hostPath:
      path: "/mnt/nvme/mlops"
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - red
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: machine-learning-operator-pv-claim
  namespace: ml
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: ml
      component: machine-learning-operator
